package com.example.quantumscan;

import java.util.ArrayList;
import java.util.List;

/*
  Todo: 0. to decide the structure of the Firebase database like how we store the data/info
        1. to decide whether to use FireBaseConnection to address the Database part OR to address it in other places OR to address in this class
        2. to add or change the methods
        3. to consistently update the code to make it works with other classes
        4. to fix the rest of the code
  The entire Class will probably be changed in the future.
*/

/**
 * This is a class that defines an Event, which can be uniquely identified by its 'id'.
 */
public class Event {
    /**
     * Int: an unique id that will not changed until the event got deleted
     *      default value is 0, indicating the Event has not changed the id.
     *      The place where generate or initialize a new Event should be responsible of setting the new ID!! (call CodeManger).
     */
    private int id;
    /**
     * String: the title of the event
     */
    private String title;
    /**
     * String: a piece of string that represents the announcement
     */
    private String announcement;
    /**
     * String: a piece of string that represents the info/description of the event
     */
    private String description;
    /**
     * ArrayList<Attendee>: an ArrayList that contains the attendees who are signed up in
     */
    private ArrayList<Attendee> attendees;
    /**
     * ArrayList<Attendee>: an ArrayList that contains the attendees who have checked in
     */
    private ArrayList<Attendee> checkedInList;
    /**
     * Organizer: the owner of the event
     */
    private Organizer organizer;  // this could also be an ArrayList<Organizer>, but temporarily we assume only one Organizer per Event now
    /**
     * String: an UNIQUE eventCode that can be scanned by the Attendee BUT it can be changed at any time
     */
    private String eventCode;  // could be also int type, we will see, share the same code base with descrCode
    /**
     * String: an UNIQUE eventCode that can be scanned by the Attendee BUT it can be changed at any time
     */
    private String descrCode;  // could be also int type, share the same code base with eventCode
    /**
     * String: the URL of the poster of the Event
     */
    private String posterCode;  // The URL of the poster
    /**
     * FirebaseFirestore: used to connect to Firebase and save/restore data from it
     */
    // private FirebaseFirestore db;  // it could be changed using Firebase Class instead of a variable? Or do it in-place

    // Constructor
    public Event() {
        this.id = 0;  // Call CodeManger's methods there This would typically be generated by a CodeGenerator/CodeManger class
        this.title = null;
        this.announcement = null;
        this.description = null;
        this.attendees = new ArrayList<Attendee>();
        this.checkedInList = new ArrayList<Attendee>();
        this.organizer = null;  // the caller should be responsible for assigning the organizer since every event should have one organizer.
        // US 01.01.01 As an organizer, I want to create a new event and generate a unique QR code for attendee check-ins.
        this.eventCode = "PLACE_HOLDER"; // Call CodeManger's methods there This would typically be generated by a CodeGenerator/CodeManger class
        this.descrCode = null; // Default is NULL/no descrCode. This would typically be generated by a CodeGenerator/CodeManger class
        this.posterCode = null; // default is null, indicating no poster

        // Initialize Firebase reference
        // Could use FirebaseConnection Class or do it somewhere else instead of in this class. Currently commented out for now.
        // this.db = FirebaseDatabase.getInstance();
    }

    public Event(Organizer organizer) {
        this.id = 0;  // Call CodeManger's methods there This would typically be generated by a CodeGenerator/CodeManger class
        this.title = null;
        this.announcement = null;
        this.description = null;
        this.attendees = new ArrayList<Attendee>();
        this.checkedInList = new ArrayList<Attendee>();
        this.organizer = organizer;
        // US 01.01.01 As an organizer, I want to create a new event and generate a unique QR code for attendee check-ins.
        this.eventCode = "PLACE_HOLDER"; // Call CodeManger's methods there This would typically be generated by a CodeGenerator/CodeManger class
        this.descrCode = null; // Default is NULL/no descrCode. This would typically be generated by a CodeGenerator/CodeManger class
        this.posterCode = null; // default is null, indicating no poster

        // Initialize Firebase reference
        // Could use FirebaseConnection Class or do it somewhere else instead of in this class. Currently commented out for now.
        // this.db = FirebaseDatabase.getInstance();
    }

    public Event(int id, String title, String description) {
        this.id = id;  // This would typically be generated by a CodeGenerator/CodeManger class
        this.title = title;
        this.announcement = null;
        this.description = description;
        this.attendees = new ArrayList<Attendee>();
        this.checkedInList = new ArrayList<Attendee>();
        this.organizer = null;  // the caller should be responsible for assigning the organizer since every event should have one organizer.
        // US 01.01.01 As an organizer, I want to create a new event and generate a unique QR code for attendee check-ins.
        this.eventCode = "PLACE_HOLDER"; // Call CodeManger's methods there This would typically be generated by a CodeGenerator/CodeManger class
        this.descrCode = null; // Default is NULL/no descrCode. This would typically be generated by a CodeGenerator/CodeManger class
        this.posterCode = null; // default is null, indicating no poster

        // Initialize Firebase reference
        // Could use FirebaseConnection Class or do it somewhere else instead of in this class. Currently commented out for now.
        // this.db = FirebaseDatabase.getInstance();
    }

    // Getters and setters for the announcement

    /**
     * This returns the id of the Event
     * @return
     *  Returns the id of the Event
     */
    public int getId() {
        return id;
    }

    /**
     * This sets the id of the Event
     * @param id
     *  The id of the Event
     */
    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This returns the announcement of the Event
     * @return
     *  The announcement of the Event (String)
     */
    public String getAnnouncement() {
        return announcement;
    }


    /**
     * This sets the announcement of the Event
     * @param announcement
     *  The announcement of the Event (String)
     */
    public void setAnnouncement(String announcement) {
        this.announcement = announcement;
    }

    // Getters and setters for event information/descr
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    // Getters for attendees
//    /**
//     * This returns the COPY of the attendee list
//     * @return
//     *  new ArrayList<>(attendees)
//     */
//    public List<Attendee> getAttendees() {
//        return new ArrayList<>(attendees); // Return a copy of the attendees list
//    }

    // US 01.10.01: As an organizer, I want to see who is signed up to attend my event.
    /**
     * This return the signed up attendee list (not the value, but the direct reference)
     * @return
     *  ArrayList<Attendee>: ths signed up list of attendees
     */
    public ArrayList<Attendee> getAttendees() {
        return attendees;
    }


    // US 01.02.01: As an organizer, I want to view the list of attendees who have checked in to my event.
    /**
     * This returns the checked-in attendee list (not the copy but the direct reference)
     * @return
     *  new ArrayList<>(attendees)
     */
    public ArrayList<Attendee> getCheckedInList() {
        return checkedInList;
    }





    /**
     * This set the new checkedInList
     * @param checkedInList
     *  Arraylist<Attendee>
     */
    public void setCheckedInList(ArrayList<Attendee> checkedInList) {
        this.checkedInList = checkedInList;
    }

    // Getters and setters for the organizer
    public Organizer getOrganizer() {
        return organizer;
    }

    /**
     * This sets the Organizer of the Event
     * @param organizer
     *  (Organizer object) representing the organizer
     */
    public void setOrganizer(Organizer organizer) {
        this.organizer = organizer;
    }

    // Getters and setters for the event code
    public String getEventCode() {
        return eventCode;
    }

    public void setEventCode(String eventCode) {
        this.eventCode = eventCode;
    }

    public String getDescrCode() {
        return descrCode;
    }

    public void setDescrCode(String descrCode) {
        this.descrCode = descrCode;
    }

    public String getPosterCode() {
        return posterCode;
    }

    public void setPosterCode(String posterCode) {
        this.posterCode = posterCode;
    }

    // methods
    // Method to add an attendee to the event
    /**
     * This adds one single Attendee object into the Attendee list
     * @param attendee
     *  The object of one single Attendee
     */
    public void addAttendee(Attendee attendee) {
        // Locally
        this.attendees.add(attendee);

        // Todo: add and save data in Firebase
        // Firebase
        // Code there
    }

    // remove/delete one Attendee from the checked-in list by passing Attendee object

    /**
     * This removes/deletes one single Attendee object from the signed up attendee list by passing Attendee object
     * @param attendee
     *  Attendee: an object of Attendee
     */
    public void deleteAttendee(Attendee attendee) {
        // Todo: remove/delete data in Firebase
        // Firebase
        // code there

        // Locally
        this.attendees.remove(attendee);
    }

    // Method to add an attendee to the checked-in list of the event
    /**
     * This adds one single Attendee object into the checked-in Attendee list
     * @param attendee
     *  The object of one single Attendee
     */
    public void addCheckedInList(Attendee attendee) {
        // Locally
        this.checkedInList.add(attendee);

        // Todo: add and save data in Firebase (if needed)
        // Firebase
        // Code there
    }

    // remove/delete one Attendee from the checked-in list by passing Attendee object

    /**
     * This removes/deletes one single Attendee object from the checked-in attendee list by passing Attendee object
     * @param attendee
     *  The object of one single Attendee
     */
    public void deleteCheckedInAttendee(Attendee attendee) {
        // Todo: remove/delete data in Firebase (if needed)
        // Firebase
        // code there

        // Locally
        this.checkedInList.remove(attendee);
    }

    // US 01.01.02: Reuse an existing QR code for attendee check-ins
    public void setExistingQRCode(String qrCodeUrl) {
        // Todo: adjust this part. What is the definition of the "existing QR code"?
        this.eventCode = qrCodeUrl;  // not sure how this works, this will be changed in the future

        // Todo: address this part, decide to use FireBaseConnection to store OR in other Classes/places OR to address there(below)
        // Update the QR code URL in Firebase
        // i.e. (no correctness guaranteed, 99% probability wrong):  note that we haven't decided the structure of the database and how we save the QR code
        // HashMap<String, String> data = new HashMap<>();
        // data.put("Event", event.getEventCode());
        // db.collection("events").document(event.getId()).set(data);
    }

    // US 01.01.03: Edit the description of the event
    public void editDescription(String newDescription) {
        // save the info/descr in the local
        this.setDescription(newDescription);

        // Todo: address the way we save in the database or do it in FireBaseConnection or in other Classes/places (to be discussed)
        // Update the description in Firebase
        // eventRef.child("description").setValue(description);  // not correctness guaranteed
    }

    // US 01.04.01: As an organizer, I want to upload an event poster to provide visual information to attendees.
    public void uploadPoster(String posterURL) {
        // Update the poster URL / poster picture locally
        this.setPosterCode(posterURL);

        // Todo: address the way we save the poster in the database or do it in FireBaseConnection or in other Classes/places (to be discussed)
        // Update the poster in Firebase
        // code there
    }

    // US 01.07.01: As an organizer, I want to create a new event and generate a unique promotion QR code that links to the event description and event poster in the app.
    public void generateDescrCode() {
        // Todo: replace the code with CodeManger's methods.
        // Change and save locally.
        // Need to call the method of CodeManger to generate the code.
        String newDescrCode = "Place_holder";  // call CodeManger's method there
        this.setDescrCode(newDescrCode);

        // Todo: address the way we save poster in the database or do it in FireBaseConnection or in other Classes/places (to be discussed)
        // Update the DescrCode in Firebase Database
        // Code there
    }

    // US 01.10.01: As an organizer, I want to see who is signed up to attend my event.
    // US 01.02.01: As an organizer, I want to view the list of attendees who have checked in to my event.
    // just directly call the getter methods of the attendees and checkedInList above
}
